### ISSUE TITLE
How can I view source code while debugging in Unity

### ISSUE THREAD

**Issue by rogetsss** [outerminds/Entia.Unity#13]
I'm trying to understand how the code works in Entia, but it is very hard to do so if I can't dig into Entia's source files. Is there a way to attach to Unity in Visual Studio and break into Entia?

**Comment by Magicolo** [comment]
You might be able to enable stepping through decompiled source code if you're using Visual Studio. In _'Tools/Options/Debugging/General'_, there should an option named _'Show disassembly if source is not available'_ which should be checked.
