### ISSUE TITLE
Entia calls React for OnAdd Messages in Editor Mode

### ISSUE THREAD

**Issue by outermindsjp** [outerminds/Entia.Unity#15]
A service with a IReact<OnAdd<ComponentType>> interface implementation will receive callbacks to the matching React method implementation while in edit mode. This will occur without Initialize being called if IInitialize is implemented, which is rather counter-intuitive.

**Comment by Magicolo** [comment]
I've fixed the issue by adding a 'Editor' node that will now be required for systems to be executed at edit time. Will be available in next version.
